CREATE DATABASE IF NOT EXISTS `users`;
CREATE DATABASE IF NOT EXISTS `events`;
CREATE DATABASE IF NOT EXISTS `groups`;
CREATE DATABASE IF NOT EXISTS `web`;
CREATE DATABASE IF NOT EXISTS `calculator`;
CREATE DATABASE IF NOT EXISTS `auth`;