name: Docker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: code
        uses: actions/checkout@v3

      - name: Docker
        uses: docker/setup-buildx-action@v2

      - name: Docker Hub login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: image
        run: |
          docker build -t my-app-image .
