# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: —Åode
        uses: actions/checkout@v2

      - name: Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.16.0'

      - name: dependencies
        run: npm install
        working-directory: ./EcoTraceServer

      - name: check for jest
        run: npm list jest 

      - name: tests
        run: npx jest --verbose
        working-directory: ./EcoTraceServer
